### ISSUE TITLE
Error in run  fit-glm-hmm.ipynb

### ISSUE THREAD

**Issue by KelvinTao** [irisstone/glmhmm#1]
Hi, Irisstone
    I run  examples/fit-glm-hmm.ipynb, and meet errors in 
    5. Fit the model
    ... 
      lls_all[i,:],A_all[i,:,:],w_all[i,:,:],pi0 = true_GLMHMM.fit(true_y,true_x,A_init,w_init) # fit the model
    ...

Error is here:

/.conda/envs/glmhmm-emission/lib/python3.7/site-packages/numpy/core/shape_base.py:78: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ary = asanyarray(ary)
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "1_fit-glm-hmm.py", line 54, in <module>
    lls_all[i,:],A_all[i,:,:],w_all[i,:,:],pi0 = true_GLMHMM.fit(true_y,true_x,A_init,w_init) # fit the model
  File "/GPFS/liying_lab_permanent/taoxianming/rat/script/skeleton_prediction/glmhmm-emission/glmhmm/glm_hmm.py", line 286, in fit
    A,w,phi,pi0 = self._updateParams(y,x,self.pStates,beta,alpha,cs,A,phi,w,fit_init_states = fit_init_states)
  File "/GPFS/liying_lab_permanent/taoxianming/rat/script/skeleton_prediction/glmhmm-emission/glmhmm/glm_hmm.py", line 215, in _updateParams
    self.w, self.phi = self._updateObservations(y,x,w,gammas)
  File "/GPFS/liying_lab_permanent/taoxianming/rat/script/skeleton_prediction/glmhmm-emission/glmhmm/glm_hmm.py", line 187, in _updateObservations
    self.w[zk,:,:], self.phi[:,zk,:] = self.glm.fit(x,w[zk,:,:],yy,compHess=self.hessian,gammas=gammas[:,zk],gaussianPrior=self.gaussianPrior)
  File "/GPFS/liying_lab_permanent/taoxianming/rat/script/skeleton_prediction/glmhmm-emission/glmhmm/glm.py", line 245, in fit
    OptimizeResult = optimize.minimize(value_and_grad(opt_log),w_flat, jac = "True", method = "L-BFGS-B")
  File "/home/liying_lab/taoxianming/.conda/envs/glmhmm-emission/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 624, in minimize
    callback=callback, **options)
  File "/home/liying_lab/taoxianming/.conda/envs/glmhmm-emission/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 308, in _minimize_lbfgsb
    finite_diff_rel_step=finite_diff_rel_step)
  File "/home/liying_lab/taoxianming/.conda/envs/glmhmm-emission/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 262, in _prepare_scalar_function
    finite_diff_rel_step, bounds, epsilon=epsilon)
  File "/home/liying_lab/taoxianming/.conda/envs/glmhmm-emission/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 159, in __init__
    self._update_grad()
  File "/home/liying_lab/taoxianming/.conda/envs/glmhmm-emission/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 238, in _update_grad
    self._update_grad_impl()
  File "/home/liying_lab/taoxianming/.conda/envs/glmhmm-emission/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 156, in update_grad
    **finite_diff_options)
  File "/home/liying_lab/taoxianming/.conda/envs/glmhmm-emission/lib/python3.7/site-packages/scipy/optimize/_numdiff.py", line 487, in approx_derivative
    use_one_sided, method)
  File "/home/liying_lab/taoxianming/.conda/envs/glmhmm-emission/lib/python3.7/site-packages/scipy/optimize/_numdiff.py", line 579, in _dense_difference
    J_transposed[i] = df / dx
ValueError: setting an array element with a sequence.
______________

It seems numpy error leading to optimize error.
I install the numpy=1.16.4, python=3.7.3, scipy=1.3.0, scikit-learn=1.0.2

How do you think what's not suitable ?

**Comment by KelvinTao** [comment]
Solved, the version problem of numpy and scipy, they should be installed by pip.

**Comment by QiGuangyao** [comment]
> Solved, the version problem of numpy and scipy, they should be installed by pip.

I reinstalled the numpy-1.21.6  and scipy-1.7.3 by pip. But the same error still happened. Could you tell me which versions are suitable?

**Comment by QiGuangyao** [comment]
> 

I reinstall the numpy-1.17.4 and scipy-1.3.0 by pip. Now it seems OK.
